### ISSUE TITLE
 ERROR: Entering a unknown email crashes the app

### ISSUE THREAD

**Issue by AxAks** [AxAks/P11_Gudlft#1]
When:

A user types in an email not found in the system

Then:
`App crashes`

Expected:
`
Code should be written to ensure that if something goes wrong (like the email isn't found), the error is caught and handled. Display an error message like "Sorry, that email wasn't found." `

The summary should be displayed to the user when a correct email is entered.

**Comment by gajendra0180** [comment]
Hello, I would like to work upon this issue. I have set up the code on my local system and is analysing the code.

**Comment by gajendra0180** [comment]
I have made a PR regarding the same Issue.Thanks.

**Comment by AxAks** [comment]
@gajendra0180 
bad idea !! :-) This is a study project, i have to do it myself ... 

You forked my project but you weren't supposed to. I will switch to a  private project 
You can get the initial project at :  https://github.com/OpenClassrooms-Student-Center/Python_Testing
(i don't think you will be authorized to send pull request there either)
  
Have fun !

**Comment by gajendra0180** [comment]
:) Sorry I wasn't knowing that.By the way it was real fun. Thanks.
